import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  alternates: {
    canonical: "https://debtremover.co.uk",
  },
  icons: {
    icon: [
      { url: "/favicon.svg", type: "image/svg+xml" },
    ],
  },
  manifest: "/site.webmanifest",
  openGraph: {
    title: "Budget Tracker — Take Control of Your Money",
    description: "Free budget tracker app. Track expenses, manage debt, and plan your monthly finances. Used by real people to get out of debt.",
    url: "https://debtremover.co.uk",
    siteName: "Debt Remover",
    images: [
      {
        url: "https://debtremover.co.uk/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Debt Remover Budget Tracker",
      },
    ],
    locale: "en_GB",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Budget Tracker — Take Control of Your Money",
    description: "Free budget tracker app. Track expenses, manage debt, and plan your monthly finances.",
    images: ["https://debtremover.co.uk/og-image.jpg"],
    creator: "@gines18",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
